### ISSUE TITLE
02828884_sdf_samples.zip don't contain ground turth mesh files.

### ISSUE THREAD

**Issue by fusheng-ji** [lity20/DCCDIF#1]
As the title above, 02828884_sdf_samples.zip only contain sampled points. I am trying to compute gt SDF by provided programs, wish you can update the zip file.

**Comment by lity20** [comment]
Sorry for my late reply.
We won't upload the mesh files as these files are very large. You can download the origin data from https://shapenet.org/, and then get the watertight meshes using tools from https://github.com/autonomousvision/occupancy_networks .

I hope this is helpful.

**Comment by fusheng-ji** [comment]
Thanks for your reply.
