### ISSUE TITLE
How to get gt_mesh?

### ISSUE THREAD

**Issue by shengjun-zhang** [lity20/DCCDIF#2]
Hello. I wonder if the gt_mesh is the orginal file named `model_normalized.obj` in ShapeNet dataset. However, if I treat these file as gt_mesh, error `AttributeError: 'Scene' object has no attribute 'sample'` occurs. I replaced `gt_mesh = trimesh.load(gt_mesh_path)` by `gt_mesh = trimesh.load_mesh(gt_mesh_path)`, but it got wrong evaluation erros.

**Comment by lity20** [comment]
The `gt_mesh` are objects from the ShapeNet dataset after several preprocessing steps. In short, you need to:
(a) generate watertight meshes from the original files (we use tools from [OccNet](https://github.com/autonomousvision/occupancy_networks).)
(b) normalize them into an unit cube.

Hope this is helpful.
