### ISSUE TITLE
About groundtruth mesh simplification

### ISSUE THREAD

**Issue by YuanxunLu** [lity20/DCCDIF#3]
Thanks for your impressive work! Here I have a question about the groundtruth mesh generation.

As you illustrated before, the groundtruth ShapeNet mesh can be generated by tools provided by 'occupancy_network'. I found that the entire generation pipeline includes scaling meshes into unit, generating the watertight mesh, and finally simplifying the complex watertight mesh. I follow the steps but I found the last simplification step degrades the mesh quality to some extent (different class suffers the degradation problem at different levels, such as the car class suffers a lot while the chair class is not).

Therefore I wonder whether you apply the simplification processing in your groundtruth meshes?

Thanks again and hope for your feedback!

**Comment by lity20** [comment]
We didn't apply the simplification step.

We get the ground truth meshes according to the instructions [here](https://github.com/autonomousvision/occupancy_networks#building-the-dataset). The file [**scripts/dataset_shapenet/build.sh**](https://github.com/autonomousvision/occupancy_networks/blob/master/scripts/dataset_shapenet/build.sh) is executed. In this file you can find that the simplification step is not performed.

Hope it helps.

**Comment by YuanxunLu** [comment]
Thanks for your reply!
