### ISSUE TITLE
.obj file for evaluation

### ISSUE THREAD

**Issue by shengjun-zhang** [lity20/DCCDIF#4]
hello. I wonder the .obj file in`   gt_mesh_path = os.path.join(config['evaluate']['gt_mesh_dir'], shape_id+'.obj')` is the .obj file in the original dataset "ShapeNetCore.v1". However, if I use these .obj files as groundtruth, I got large CD loss which is not right obviously. But the watertight mesh you mentioned before is performed in .off files. Thanks!

**Comment by lity20** [comment]
The `.obj` files in `gt_mesh_path` is the watertight meshes.
I'm sorry to confuse you. I convert the `.off` files produced by tools from OccNet to `.obj` format. But there is no difference except for the file format.
