### ISSUE TITLE
Results on Thingi32 Dataset

### ISSUE THREAD

**Issue by YuanxunLu** [lity20/DCCDIF#5]
Thanks for your impressive work! This repo currently contains your official checkpoints results of ShapeNet, while the results on the single object dataset, i.e., Thingi32, are not included. Would you have any plan to release these results? That will be greatly helpful for comparisons~

Thanks again for your fantastic work!

**Comment by lity20** [comment]
Sorry, I only archived code and checkpoint files for the ShapeNet experiment. But, basing on the existing code and the description in paper, you can easily reproduce the experiment on Thingi32.
