### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by mah-asd** [lity20/DCCDIF#6]
Hi Thank you for providing the code, this work is great. 
I have a question about using your code. Do you think it is feasible to replace ConvONet with DCC-DIF in a SLAM system? Just changing the module. 
Thanks in advance

**Comment by lity20** [comment]
Without adjusting the implementation, it is not feasible to directly use it in a SLAM system.
In a SLAM system, the CPL (code position loss) is difficult to calculate. Thus, you need to consider alternative solutions to provide guidance for the location of latent codes.

**Comment by mah-asd** [comment]
Thank you!
